[package]
name = "eris"
version = "0.2.4"
edition = "2021"
authors = ["Xqhare"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.30.5"
json = "0.12.4"
chrono = "0.4.31"
