[package]
name = "eris"
version = "0.1.3"
edition = "2021"
authors = ["Xqhare"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.30.5"
neith = { path = "../neith" }
json = "0.12.4"
